name: CI Workflow

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  build:
    runs-on: self-hosted # Indicates that this job will run on a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x' # Change this to the desired .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore


      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-app
          path: /home/compar/testdeploy # Replace with the actual path to your published folder
