name: Deploy To DigitalOcean
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Create deploy directory
        run: mkdir -p /home/compar/deploy/WebUI

      - name: Publish WebUI project
        run: |
          dotnet publish /path/to/WebUI.csproj -c Release -o /home/compar/deploy/WebUI --no-restore --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: /home/compar/deploy/WebUI
