name: Deploy To Digital Ocean

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
  
      - name: Install dependencies
        run: dotnet restore -r linux-x64

      - name: Build Project
        run: | 
         cd /home/compar/actions-runner/_work/k401-digital-ocean-deploy/k401-digital-ocean-deploy/WebUI
       
      - name: Build
        run: dotnet build --configuration Release --no-restore -r linux-x64

      - name: Deploy Project
        run: |
         dotnet build
