name: Deploy To DigitalOcean
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Publish WebUI project
        run: |
          dotnet publish /home/compar/actions-runner/_work/k401-digital-ocean-deploy/k401-digital-ocean-deploy/WebUI/WebUI.csproj -c Release -o /home/compar/deploy/WebUI

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: /home/compar/deploy/WebUI

   
