name: Deploy To Digital Ocean

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Project
        run: | 
         cd /home/compar/actions-runner/_work/k401-digital-ocean-deploy/k401-digital-ocean-deploy/WebUI
         - dotnet build

      - name: Deploy Project
        run: |
          cd /home/compar/test
